name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.9'

      - name: Remove old Android folder
        run: rm -rf android

      - name: Recreate Flutter project (Android embedding v2)
        run: flutter create . --project-name masarifbinaa

      - name: Get dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: masarifbinaa-app
          path: build/app/outputs/flutter-apk/app-release.apk
